### ISSUE TITLE
Chat log isn't kept after round restart

### ISSUE THREAD

**Issue by Dendari92** [EmulatorNexus/Advanced-Chat#5]
Based on the [announcement thread](http://forums.veniceunleashed.net/viewtopic.php?f=43&t=7646) this shouldn't happen.
Example video: http://youtu.be/SVu_XqBpYF8
VU version **8312**.

**Comment by OrfeasZ** [comment]
I couldn't reproduce this in the latest build.
If you find a way to re-produce it, please update this issue with exact instructions on how to and I'll re-open it.
